version: '3.7'

services:
    app:
        image: benbergstein/us-electoral-map:latest
        volumes:
          - ./app:/app
        command: ["dev"]
        ports:
            - "8080:3000"
        networks:
          - default
          - nginx-proxy

networks:
  default:
  nginx-proxy:
    external: true
